services:
  mysql_db:
    image: mysql
    expose:
      - '3307'
    ports:
      - '3307:3307'
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_3233
      - MYSQL_DATABASE=contact-search
      - MYSQL_USER=csuser
      - MYSQL_PASSWORD=csuser123
      - MYSQL_TCP_PORT=3307

  nestjs_backend:
    depends_on:
      - mysql_db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DB_NAME=contact-search
      - DB_USER=csuser
      - DB_PASS=csuser123
      - DB_HOST=mysql_db
      - DB_PORT=3307
      - PORT=3000
      - JWT_SECRET=jwtse6reTkeyw0rd
    volumes:
      - ./src:/usr/src/app/src
